---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  annotations:
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: meliuz/shopping-cart-app-example
  description: |-
    # Welcome to your Expo app 👋

    This is an [Expo](https://expo.dev) project created with [`create-expo-
    app`](https://www.npmjs.com/package/create-expo-a...
  name: shopping-cart-app-example
spec:
  lifecycle: production
  type: service
  owner: playtime
